- name: mongodb
  hosts: mongodb
  become: yes  
  tasks:
  - name: Copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: etc/yum.repos.d/mongo.repo

  - name: Install mongodb
    ansible.builtin.package:
      name: mongo-org
      state: present

  - name: start and enable mongodb
    ansible.builtin.service:
     state: started
     enabled: yes  

  - name: allow remote connection
    ansible.builtin.replace:
     path: /etc/mongod.conf
     regexp: '127.0.0.1'
     replace: '0.0.0.0'
     
  - name: start and enable mongodb
    ansible.builtin.service: 
     name: mongodb
     state: restarted    
    

