- name: install web component
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: Remove file directory
    ansible.builtin.file:
     path: /usr/share/nginx/html
     state: absent
     
  - name: create file directory
    ansible.builtin.file:
     path: /usr/share/nginx/html
     state: absent
     
  - name: download web application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip 
      dest: /tmp

  - name: extract application
    ansible.builtin.unarchive: 
      src: /tmp/web.zip
      dest: /etc/usr/share/nginx/html
      remote_src: yes  

  - name: Copy roboshop configuration
    ansible.builtin.copy: 
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes    
